### ISSUE TITLE
[suggestion] Add Numbers To Amount Of Staff Members To your staff list!

### ISSUE THREAD

**Issue by McFanta** [StatTrack/StatTrack.github.io#44]
This Is How It Will Look Like.

<img src="//i.imgur.com/o6mRZwM.png" alt="">

Add It :laughing:!

**Comment by matic0basle** [comment]
no image?

**Comment by McFanta** [comment]
Hmm I'll fix it later. I have some wierd bugs with chrome. Can't do shot because windows are now opening chrome as an windows app!

**Comment by McFanta** [comment]
Here is the missing image <img src="//i.imgur.com/pVEVdZM.png" alt="">

Please Add It! It looks a lot better.

**Comment by McFanta** [comment]
Here Is The Missing Image. This Looks A Lot Better! Right? Add it.
![suggestion](https://cloud.githubusercontent.com/assets/13437351/12201052/7977a5a4-b622-11e5-83b9-504ef3cb2c21.png)

**Comment by matic0basle** [comment]
I'll keep this open but its not on the top of our priority list atm

**Comment by McFanta** [comment]
okay but I would like to become a developer there or Assistant :laughing:

**Comment by matic0basle** [comment]
The current ranks are like this:
 - Administrator - Pretty much me since I run the project. When I stop doing that or need help, new ones will be added.
 - Developers - Solo on this atm as well. Works on layout changes that are being done (site really needs a layout change im just lazy).
 - Assistants - Add content / shots (new ones arent added yet)

You can post on the main thread if you want to help.
